name: deploy app to aws
on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build/

  build-backend:
    runs-on: ubuntu-20.04
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Build with maven
        working-directory: backend
        run: mvn -B package
      - uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: backend/target/app.jar

  deploy-aws:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: app.jar

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name: capstone #Application name we created in Elastic BeanStalk
          environment_name: capstone-env #Environment name we created in Elastic BeanStalk
          version_label: ${{github.SHA}}
          region: eu-central-1
          deployment_package: app.jar #download artifacts from previous job
